# vim:ft=ansible:

- src: https://github.com/alphagov/openldap_server.git
  version: b6e32f3c049f9607dcbbbc743e92baf7e8a6a7d5
  name: bennojoy.openldap_server
- src: https://github.com/jnv/ansible-role-ldap-auth-client.git
  version: a5b17a5c3851207fe90fb496da4e4653d857a770
  name: jnv.ldap-auth-client
